### ISSUE TITLE
Use a rolling average that is multiple of 7 days

### ISSUE THREAD

**Issue by h-vetinari** [mayeut/manylinux-timeline#280]
The download statistics are very noisy, almost certainly driven by a split between working days (more downloads) and weekends (less downloads). It would make sense IMO to use a moving average with a length that is a multiple of seven, to make the chart more easily readable.

**Comment by mayeut** [comment]
Agreed. It's been on my mind for quite some time now and will be done when time allows. I thought at first that the fact that statistics were different on workdays than on weekends was something worth keeping. I still think it's interesting but it probably doesn't change the tendencies much and just make things harder to read (not so much that tendencies can't be read at all which explain why it's not done yet).

**Comment by h-vetinari** [comment]
Looks much better IMO (at least, easier to read), thanks a lot! :)
