### ISSUE TITLE
Global statistic for non-EOL python

### ISSUE THREAD

**Issue by h-vetinari** [mayeut/manylinux-timeline#441]
I was wondering if Python 2.7-3.6 should be dropped from the timeline - currently they're the first thing being displayed. I could also imagine them being moved to the bottom of the page under a separate header à la "Statistics for EOL Python versions".

What I'm mainly interested in is having some global consumer statistics (i.e. glibc distribution) for non-EOL python versions -- presumably this could be an additional pane, because I guess some truly global statistics about download numbers per Python version would still be interesting.

While we're at it, I'd also consider to order the python versions in reverse chronological order.

All in all, I'd propose the following revamp of the "consumer statistics" section:

**Comment by h-vetinari** [comment]
Actually, for Python>=3.10, Policy readiness == glibc readiness (since Python 3.10 includes PEP600-capable pip), so actually we could drop the "policy readiness" there. :)

**Comment by mayeut** [comment]
Thanks for all the suggestions.
I'm not in favor of dropping versions for which overall downloads are more than 1.0% just yet (so dropping 3.5 would be OK).
The proposed layout makes sense to me.
