### ISSUE TITLE
Ensure python versions get same colours

### ISSUE THREAD

**Issue by h-vetinari** [mayeut/manylinux-timeline#473]
I'm talking about the difference between the `Python version (All)` and `Python version (non-EOL)` plots; since the colours seem to be assigned in ascending order, and the non-EOL plot starts later, we get different colours for what should be the same (see below). It would be visually much easier IMO if the colours didn't change between python versions (e.g. currently Python 3.7 switches from purple to red between the plots).

![image](https://user-images.githubusercontent.com/33685575/224863343-20160f4b-7a78-4639-807c-fb15c19567ea.png)

**Comment by mayeut** [comment]
thanks for the suggestion, took me a while to get time to do this bu it's now done.
