### ISSUE TITLE
Add newer glibc versions

### ISSUE THREAD

**Issue by h-vetinari** [mayeut/manylinux-timeline#532]
I think we should add at least 2.36 & 2.39, c.f. https://github.com/mayeut/pep600_compliance/issues/362

On the other end, 2.5 and 2.12 can likely be dropped, as they're completely gone for Python >=3.7, and used for less than 1% of downloads for even older Python versions.

2.23 would be the next candidate for removal after that - it's only really relevant for the Python 3.5 plot, which is arguably not that important anymore either (as 3.5 is ~0.4% of all downloads), and could probably be dropped itself as well.

**Comment by mayeut** [comment]
versions added at 95a4cc4a0f570d097a6cc95bec70161257297802

removals will happen at a later date.

**Comment by h-vetinari** [comment]
Thanks a lot!
